ci: run the security static analysis tool bandit
Whether we run any security tooling came up during an IT review,
and it sounds like a good idea.

Its only complaint so far was about using the subprocess module at
all (low priority warning, just telling us "hey, please consider
whether you are checking validity of input"). I think we are OK
there, so I silenced those warnings on a line-by-line basis.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -51,13 +51,18 @@ jobs:
       - name: Install linters
         run: |
           python -m pip install --upgrade pip
-          pip install pycodestyle pylint
+          pip install bandit[toml] pycodestyle pylint
 
       - name: Run pycodestyle
         run: |
           pycodestyle --max-line-length=120 .
 
       - name: Run pylint
-        if: success() || failure() # still run pylint if pycodestyle fails
+        if: success() || failure() # still run pylint if above checks fail
         run: |
           pylint cumulus tests
+
+      - name: Run bandit
+        if: success() || failure() # still run bandit if above checks fail
+        run: |
+          bandit -c pyproject.toml -r .
